import os
import json

try:
    from groq import Groq
except ImportError:
    Groq = None


def _make_safe_summary(kpis, columns, insights):
    """
    Create a safe summary for the AI model.

    Important:
    We do NOT send the full CSV or Excel data.
    We only send:
    - KPIs calculated by Python
    - detected column names
    - rule-based insights
    """

    safe_summary = {
        "kpis": kpis,
        "detected_columns": columns,
        "rule_based_insights": insights,
    }

    return safe_summary


def get_gemini_insight(kpis, columns, charts=None, insights=None, api_key=None, use_case='General', lang='en'):
    """
    Generate AI business explanation using Groq (Llama 4 Scout).

    Parameters:
    - kpis: dictionary of calculated KPIs
    - columns: dictionary of detected columns
    - charts: optional chart dictionary, not sent to the AI model
    - insights: rule-based insights generated by Python
    - api_key: optional Groq API key

    Important:
    This function does NOT send raw dataset rows to the AI model.
    """

    if insights is None:
        insights = []

    # Allow API key from function argument OR environment variable
    if not api_key:
        api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        return (
            "Groq API key is not set. "
            "Showing rule-based insights only. "
            "To enable AI explanation, set GROQ_API_KEY."
        )

    if Groq is None:
        return (
            "groq package is not installed. "
            "Install it with: pip install groq"
        )

    try:
        # Initialize Groq client
        client = Groq(api_key=api_key)

        safe_summary = _make_safe_summary(kpis, columns, insights)

        if lang == 'ar':
            prompt = f"""
أنت خبير ومحلل بيانات متخصص في مجال "{use_case}" تساعد صاحب عمل غير تقني على فهم بياناته.

اشرح الملخص التالي بلغة بسيطة وموجزة جداً في سياق مجال {use_case}.

قواعد هامة جداً:
- اجعل الإجابة قصيرة جداً. بحد أقصى 4 إلى 5 نقاط.
- استخدم التنسيق (نقاط عريضة، قوائم نقطية).
- لا تخترع أي أرقام. استخدم فقط الأرقام الموجودة في الملخص.
- قدم نصائح عملية وسهلة الفهم وتتعلق بمجال {use_case}.
- يجب أن تكتب الشرح باللغة العربية حصراً.

الملخص المحسوب:
{json.dumps(safe_summary, indent=2, default=str)}

التنسيق:
- ابدأ مباشرة بالنقاط. لا تكتب أي مقدمات.
- اجعل كل نقطة مباشرة وقوية.
"""
        else:
            prompt = f"""
You are an expert data analyst specializing in the "{use_case}" domain, helping a non-technical business owner understand their data.

Explain the following calculated summary in very simple, concise language, tailored to the {use_case} industry.

Very important rules:
- Keep it SHORT. Max 4-5 bullet points total.
- Use markdown formatting (bolding, bullet points).
- Do NOT invent numbers. Only use the numbers provided in the summary.
- Give practical, easy-to-understand insights highly relevant to {use_case}.
- IMPORTANT: You MUST write the entire explanation in English.

Calculated summary:
{json.dumps(safe_summary, indent=2, default=str)}

Format:
- Start directly with the bullet points. No introductory text.
- Make each point punchy and direct.
"""

        response = client.chat.completions.create(
            model="meta-llama/llama-4-scout-17b-16e-instruct",
            messages=[
                {
                    "role": "system",
                    "content": f"You are a helpful business data analyst in the {use_case} industry. Provide clear, actionable insights in simple language."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.6,
            max_completion_tokens=1024,
        )

        if not response or not response.choices:
            return "AI model did not return an explanation."

        return response.choices[0].message.content

    except Exception as e:
        return f"Error getting AI insight: {e}"